name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate build files
      run: cmake -Bbuild -H.
    - name: Build HippoMocks
      run: cmake --build build/ --target all
    - name: Run Unit Tests
      run: build/HippoMocksTest/HippoMocksTests
